import 'package:flutter/material.dart';

const Color accent = _green,
    appBarColor = _transparent,
    textColorPrimary = _oxfordBlue,
    textColorSecondary = _secondaryBlack,
    textColorSecondary1 = _secondaryBlack1,
    textColorInverse = _white,
    textColorInactiveBlack = _inactiveBlack,
    textColorAccent = _green,
    panelBackground = _whiteGrey,
    witeBackground = _white,
    invisibleBackground = _transparent,
    dividerColor = _inactiveBlack,
    imageMockColor = _lightBlue,
    imageGradient1 = _darkBlue1,
    imageGradient2 = _darkBlue2,
    iconColor = _darkBlue2,
    activeBackground = _darkBlue2,
    unselectedIconColor = _lightBlue;

const Color _transparent = Colors.transparent,
    _oxfordBlue = Color(0xFF252849),
    _green = Color(0xFF4CAF50),
    _whiteGrey = Color(0xFFF5F5F5),
    _white = Colors.white,
    _lightBlue = Colors.blueGrey,
    _darkBlue1 = Color(0xFF252849),
    _darkBlue2 = Color(0xFF3B3E5B),
    _inactiveBlack = Color(0x8F7C7E92),
    _secondaryBlack = Color(0xFF3B3E5B),
    _secondaryBlack1 = Color(0xFF7C7E92);
